# Generated by Django 5.0.13 on 2025-12-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Hospital', '0002_alter_doctor_apellido_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_Hospital.cita'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
