# Generated by Django 5.0.13 on 2025-12-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Hospital', '0003_alter_factura_cita_alter_factura_fecha_emision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_sala', models.CharField(max_length=20, unique=True)),
                ('area', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('equipamiento', models.TextField(blank=True, null=True)),
                ('estado_mantenimiento', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=50)),
                ('nivel_seguridad', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='codigo_cita',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='duracion_estimada',
            field=models.PositiveIntegerField(default=30, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='cita',
            name='notas_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(default='Consulta General', max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='lugar_cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Hospital.sala'),
        ),
    ]
